apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: {{ .Values.services.redis.port }}
    targetPort: 6379
  selector:
    app: redis