apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: ClusterIP
  ports:
  - name: "result-service"
    port: {{ .Values.services.result.port }}
    targetPort: {{ .Values.services.result.targetPort }}
  selector:
    app: result