apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: {{ .Values.services.db.port }}
    targetPort: 5432
  selector:
    app: db