apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.ddgames.ru
  name: deckhouse-cluster
contexts:
- context:
    cluster: deckhouse-cluster
    user: read-user
  name: read-context
current-context: read-context
users:
- name: read-user
  user:
    token: eyJhbGc******qZ35w0gscg
