apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.ddgames.ru
  name: deckhouse-cluster
contexts:
- context:
    cluster: deckhouse-cluster
    user: write-user
  name: write-context
current-context: write-context
users:
- name: write-user
  user:
    token: eyJhbGc****ZthikcA
