apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.ddgames.ru
  name: deckhouse-cluster
contexts:
- context:
    cluster: deckhouse-cluster
    user: admin-user
  name: admin-context
current-context: admin-context
users:
- name: admin-user
  user:
    token: eyJhbGc****58BRjA
